### ISSUE TITLE
non-main file future compatibility

### ISSUE THREAD

**Issue by est31** [epage/cargo-script-mvs#153]
I think it's an absolutely good idea that the initial release only supports `main.rs`, but i wonder whether one could also add forward compatibility support for build.rs specified inside the file. Namely, reserving some syntax for it, or at least starting the process about thinking about syntax, so that later on when/if one implements it, the most optimal syntax is still available.

As a strawman proposal e.g. 

```rust
#!/usr/bin/env cargo-eval

fn main() {}

// cargo-eval-file: build.rs
mod build { /* ... */}
```

would indicate that the content of the module would be the content of the "build.rs" file. Unlike in Rust, these special modules would only be allowed on the top level. There are syntaxes currently forbidden by Rust, like `#[cfg(file::build_rs)]`, so one isn't out of options when not doing anything, but IMO it's good to at least do some initial brainstorming on it.

**Comment by est31** [comment]
build.rs is used for example to detect rustc compatibility. Alternatively, you might want to emit specific rustc flags in build.rs. Also I filed this issue mostly about future compatibility for build.rs.

And build.rs is only one of the use cases, other use cases are multiple invokeable binaries that share some library code, or separate lib.rs and main.rs files. If you want to build an auto conversion tool from a multi file package to a single file one, it would be nice if users wouldn't be getting error messages about the case of separate lib.rs and main.rs not being supported.

I'm not saying that this feature should be there from the get-go, just to collect some ideas about the design and then to *eventually* do it.

**Comment by epage** [comment]
FYI I'm documenting this as explicitly not supported in the Drawback to raise the visibility of this so we can further discuss this and let the relevant teams decide if this should be changed.
