### ISSUE TITLE
How do we balance reducing boilerplate in scripts while allowing reproducibility across systems

### ISSUE THREAD

**Issue by epage** [epage/cargo-script-mvs#46]
- Examples:
  - Add "always there" dependencies (e.g. `clap`)
  - Keep major versions up to date (`*` means new scripts use latest but won't be able to run old scripts)
  - Avoid boilerplate of having to specify the current edition
- Ideas:
  - Default to loose, low-boilerplate approach (always latest edition, global prelude, global dependency-list) with warning telling people to run a command to turn it into a non-loose version (sets edition, embeds prelude and dependency list with a marker to say this is running in isolated mode)

**Comment by epage** [comment]
Other ideas
- Allow templates in and settings in `.cargo` so they can be defined in your workspace with your scripts (build on #45)
- Allow specifying the template (https://github.com/fornwall/rust-script/issues/3)
- Implicit [de-duplication](https://github.com/rust-lang/cargo/issues/8415) with the workspace and/or a table in `.cargo/config`

Main risk for some of these is slowing down start up time

**Comment by bjorn3** [comment]
Another option would be to automatically copy the lockfile next to the script. For example for a `foo.rs` script it would generate a `foo.rs.lock` file. If one exists this file would be copied to `Cargo.lock` in the generated source dir and if cargo changed it, it would be copied back. You wouldn't strictly have everything in a single file anymore, but everything the user cares about would still be in a single file.

**Comment by epage** [comment]
Interesting idea
- We could possibly extend the format for `edition` so new scripts are locked in at the edition  at the time of writing
- People might hate the clutter which might kill it
- I was also wondering about #48 to improve reuse of intermediate build results
