### ISSUE TITLE
Share a lock file across scripts

### ISSUE THREAD

**Issue by epage** [epage/cargo-script-mvs#48]
This will help ensure we maximize builds, rather than always picking up the latest when a new script is created.

**Comment by samuelorji** [comment]
@epage Will it please be possible to outline what this entails in steps so I can attempt to pick it up.

**Comment by epage** [comment]
Issues tagged with "question" are going to be more vague without an idea of even if its worth doing or now.  In this case, its considering what the workflow would look like, how it interacts with other aspects (#82, #49), prototyping it (probably just put a workspace in the cache's directory), and then exploring side effects (performance of loading the entire workspace, etc).

So I'd consider this one blocked on #82 and #49 which are also questions

If you are looking for something next to do, some more concrete ideas include
- https://github.com/epage/cargo-script-mvs/issues/40
- https://github.com/epage/cargo-script-mvs/issues/43
- https://github.com/epage/cargo-script-mvs/issues/47
- https://github.com/epage/cargo-script-mvs/issues/93
- https://github.com/epage/cargo-script-mvs/issues/25 (and fixing them)
- Also merging any changes over from rust-script since the fork

**Comment by samuelorji** [comment]
Sweet ... Thanks
