### ISSUE TITLE
Default the authors to what `cargo new` does

### ISSUE THREAD

**Issue by epage** [epage/cargo-script-mvs#81]
Right now, the author is `Anonymous`.  We should do what `cargo new` does

**Comment by samuelorji** [comment]
I'm quite new to rust, but I think I remember seeing somewhere that `cargo new` [wanted to deprecate those fields](https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_new.rs#L133).

But if we still wanna go ahead with it, I guess a simple thing is to parse it from the `.gitconfig`, and probably add an optional argument for the author name and email like `--author_name` and `--author_email` .
WDYT?

**Comment by epage** [comment]
We should drop the author field like cargo-new

**Comment by samuelorji** [comment]
okay 👍

**Comment by epage** [comment]
See #92
